# site settings
title: Julian Møller Ellehauge
description: "The weblog on programming by Julian Møller Ellehauge."

url: "https://www.jumoel.com"
baseurl: "/"

timezone: Europe/Copenhagen

date_format: "%b %-d, %Y"

email: "contact-jumoel-com@jumoel.com"
username:
  github: jumoel
  linkedin: jumoel

latest_posts_num: 10

host: 0.0.0.0

defaults:
  - scope: { path: "", type: "pages" }
    values: { layout: "default" }
  - scope: { path: "", type: "posts" }
    values: { layout: "post" }

# Build settings
destination: _build
markdown: CommonMarkGhPages
commonmark:
  options: ["UNSAFE", "SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]
  syntax_highlighter: rouge
permalink: /posts/:title

# Conform to GitHub Pages defaults
safe: true
lsi: false
